disabled_rules:
- identifier_name
- function_body_length
- trailing_whitespace
- type_name
- file_length

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- docs
- img
- spec
- Project-Meta

line_length:
- 199 # warning
- 200 # error

cyclomatic_complexity:
- 7 # warning
- 10 # error
