disabled_rules:
- identifier_name
- function_body_length
- trailing_whitespace
- type_name
- file_length
- nesting

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- docs
- img
- spec
- Project-Meta

line_length:
- 299 # warning
- 300 # error

cyclomatic_complexity:
- 9 # warning
- 10 # error
