disabled_rules:
- identifier_name
- function_body_length
- trailing_whitespace
- type_name
- file_length
- nesting
- leading_whitespace
- trailing_newline

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- docs
- img
- spec
- Project-Meta

type_body_length:
- 299 # warning
- 300 # error

line_length:
- 299 # warning
- 300 # error

cyclomatic_complexity:
- 20 # warning
- 30 # error
